### ISSUE TITLE
Error when inserting notes

### ISSUE THREAD

**Issue by elyrank** [bullhorn/sdk-rest#158]
Hi,
I have started using the Bullhorn API a few days ago , and working on the integration.
I tried to add Notes to candidate in two ways (both failed)

1. Using the candidate: 
candidate.setNotes(OneToMany<Note> notes) 

I get this warning  on the candidate update and the note is not added:
```
 UpdateResponse {
changedEntityType=Candidate, 
changedEntityId=18, 
changeType=UPDATE, 
messages=[ {
detailMessage=null, 
propertyName=notes, 
severity=WARNING, 
type=ATTEMPT_TO_SET_TO_MANY
}], 
errorCode=, 
errorMessage=
}>
```

2. Using the addNoteAndAssociateWithEntity()
I get exceptions but the note is inserted.

```

com.bullhornsdk.data.exception.RestApiException: {
  "errorMessage" : "error persisting an entity of type: NoteEntity",
  "errorMessageKey" : "errors.cannotPersistEntity",
  "errorCode" : 500,
  "errors" : [ {
    "propertyName" : null,
    "severity" : "ERROR",
    "type" : "DUPLICATE_VALUE"
  } ],
  "entityName" : "NoteEntity"
}
	at com.bullhornsdk.data.api.StandardBullhornData.handleHttpStatusCodeError(StandardBullhornData.java:1855)
	at com.bullhornsdk.data.api.StandardBullhornData.performCustomRequest(StandardBullhornData.java:1832)
	at com.bullhornsdk.data.api.StandardBullhornData.handleInsertEntity(StandardBullhornData.java:1036)
	at com.bullhornsdk.data.api.StandardBullhornData.insertEntity(StandardBullhornData.java:313)
	at com.bullhornsdk.data.api.StandardBullhornData.handleAddNoteAndAssociateToEntity(StandardBullhornData.java:617)
	at com.bullhornsdk.data.api.StandardBullhornData.addNoteAndAssociateWithEntity(StandardBullhornData.java:544)
```

This is how I create the note:

           
		Person commentingPerson = new Person(1);
		Person personReference = new Person(candidateId);
		Note note = new Note();
		note.setCommentingPerson(commentingPerson);
		note.setPersonReference(personReference);
		note.setComments("my comment"));

Is this a bug or am I doing something wrong?

**Comment by ndickerson** [comment]
Hi Elyran,

You are correct on the first method, `candidate.setNotes(OneToMany notes)`. To-One Associations can be made in the create call, but To-Many Associations normally have to be made after the create call, in a separate Associate call for each of the associations. I say normally, because right now we are actually rolling out a change that is particular to Notes, where we allow the create call to set all To-Many associations. This is available on BHNext today, and will be rolled out everywhere on July 18. If you are on the latest version of the SDK, v1.2.11 (https://search.maven.org/#search%7Cga%7C1%7Cbullhorn), then you can create notes using the first method, and it will generate the note and all associations with a single REST call.

This works now:
```
        Note note = new Note();
        note.setComments("My Note with SDK v1.2.11 - with 2 referenced candidates");

        Person personReference = new Person(1);
        note.setPersonReference(personReference);

        List<Candidate> candidateList = new ArrayList<>();
        Candidate candidate1 = new Candidate(2);
        Candidate candidate2 = new Candidate(3);
        candidateList.add(candidate1);
        candidateList.add(candidate2);

        OneToMany<Candidate> candidateOneToMany = new OneToMany<>();
        candidateOneToMany.setData(candidateList);
        note.setCandidates(candidateOneToMany);

        CrudResponse crudResponse = bullhornData.insertEntity(note);
```

As far as step 2, that is a bug, since the call errors out after setting the person reference, which prevents further associations from being created. I will keep this issue open in order to track that bug.

Thanks,
Nathan
