### ISSUE TITLE
concurrent modification exception on association list 

### ISSUE THREAD

**Issue by elyrank** [bullhorn/sdk-rest#166]
The actual bug is in allAssociations() method:
```
 if (allAssociations == null) {
            allAssociations = new ArrayList<AssociationField<Candidate, ? extends BullhornEntity>>();
            allAssociations.add(businessSectors());
...
```
it is the same for all association entities

```

java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.bullhornsdk.data.model.entity.association.standard.CandidateAssociations.getAssociation(CandidateAssociations.java:162)
        at com.bullhornsdk.data.model.entity.association.AssociationFactory.getAssociationField(AssociationFactory.java:50)

```
using version 1.2.10

**Comment by ndickerson** [comment]
Hi Elyran,

This is the same issue that we had in DataLoader, and solved by wrapping in a `synchronized` method:

```
    /**
     * Returns the list of associated fields for the given SDK-REST entity class.
     * <p>
     * Synchronized to avoid race condition when multiple tasks are initializing at the same time on their
     * different threads, and all calling this method the first time through.
     *
     * @param entityClass The SDK-REST entity class
     * @return The list of this entity (key is always this entity class) to the entity's associated classes
     */
    public static synchronized List<AssociationField<AssociationEntity, BullhornEntity>> getAssociationFields(Class entityClass) {
        try {
            if (entityClassToAssociationsMap.containsKey(entityClass)) {
                return entityClassToAssociationsMap.get(entityClass);
            } else {
                EntityAssociations entityAssociations = getEntityAssociations(entityClass);
                List<AssociationField<AssociationEntity, BullhornEntity>> associationFields = entityAssociations.allAssociations();
                entityClassToAssociationsMap.put(entityClass, associationFields);
                return associationFields;
            }
        } catch (Exception e) {
            return new ArrayList<>();
        }
    }
```

I will look into fixing this in the SDK to avoid the need to synchronize this step across threads.

Thanks,
Nathan
