### ISSUE TITLE
API Authentication Issue

### ISSUE THREAD

**Issue by guru257525** [bullhorn/sdk-rest#263]
Hi Team,

We have received Bullhorn API credentials from your support team as below.
Client ID: 489b8ddf-2b30-43a9-a348-0153ec666ecd
Client Secret: QhTJ7W5avaBzLj7t8RjWcQQU

Username: findrecruitment.api
Password: Ow1um0qLWZnCPj2!

The Authentication fails with the below exception
Exception in thread "main" com.bullhornsdk.data.exception.RestApiException: Failed to create rest session
	at com.bullhornsdk.data.api.helper.RestApiSession.createSession(RestApiSession.java:136)
	at com.bullhornsdk.data.api.helper.RestApiSession.<init>(RestApiSession.java:88)
	at com.bullhornsdk.data.api.StandardBullhornData.<init>(StandardBullhornData.java:165)
	at com.avrio.bullhorn.BullhornPullUtil.main(BullhornPullUtil.java:101)
Caused by: com.bullhornsdk.data.exception.RestApiException: Failed to get authorization code.
	at com.bullhornsdk.data.api.helper.RestApiSession.getAuthorizationCode(RestApiSession.java:165)
	at com.bullhornsdk.data.api.helper.RestApiSession.createSession(RestApiSession.java:126)
	... 3 more
Caused by: java.lang.NullPointerException
	at com.bullhornsdk.data.api.helper.RestApiSession.getAuthCode(RestApiSession.java:191)
	at com.bullhornsdk.data.api.helper.RestApiSession.getAuthorizationCode(RestApiSession.java:162)
	... 4 more

Let me know if you need anything else.

**Comment by andrewsavill** [comment]
Hi @guru257525, 

Not sure you should share your private credentials on a public site.  You might want to delete them from this post.

**Comment by guru257525** [comment]
Hi @andrewsavill,

I have removed it, let me know if you need anything else to debug this issue.

**Comment by guru257525** [comment]
Hi,

Any update on this issue?

**Comment by charlesabarnes** [comment]
Hey @guru257525, apologies for your wait.  

Have you tried to manually run through the API auth steps? This would possibly help us diagnose which step of the process this is failing at.  

The manual steps can be found here: http://bullhorn.github.io/Getting-Started-with-REST/

Please let me know if I can help you with this

**Comment by guru257525** [comment]
HI @charlesabarnes,

Itseems to be working now, I did not make any changes though.

Will let you know if anything goes wrong again

Thanks

**Comment by joncampbelldev** [comment]
Just to let you know that past versions of comments are visible on github, you should definitely revoke those credentials. They're still visible by clicking on the "edited" button next to the initial post. Hopefully you have done this already because anyone could've been accessing your data for the last 6 months.

**Comment by joncampbelldev** [comment]
@guru257525 (mentioning you just in case the above comment didn't notify you)
